/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ICommunityInterface extends utils.Interface {
  contractName: "ICommunity";
  functions: {
    "configure(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "configure",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;

  events: {
    "ConfigurationUpdate(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConfigurationUpdate"): EventFragment;
}

export type ConfigurationUpdateEvent = TypedEvent<
  [string, BigNumber],
  { commerceToken: string; membershipPrice: BigNumber }
>;

export type ConfigurationUpdateEventFilter =
  TypedEventFilter<ConfigurationUpdateEvent>;

export interface ICommunity extends BaseContract {
  contractName: "ICommunity";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICommunityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    configure(
      _commerceToken: string,
      _membershipPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  configure(
    _commerceToken: string,
    _membershipPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    configure(
      _commerceToken: string,
      _membershipPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ConfigurationUpdate(address,uint256)"(
      commerceToken?: string | null,
      membershipPrice?: BigNumberish | null
    ): ConfigurationUpdateEventFilter;
    ConfigurationUpdate(
      commerceToken?: string | null,
      membershipPrice?: BigNumberish | null
    ): ConfigurationUpdateEventFilter;
  };

  estimateGas: {
    configure(
      _commerceToken: string,
      _membershipPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    configure(
      _commerceToken: string,
      _membershipPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
