/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ICreatorAccessInterface extends utils.Interface {
  contractName: "ICreatorAccess";
  functions: {
    "totalCreatorRewardsAccumulated()": FunctionFragment;
    "withdrawCreatorRewards()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "totalCreatorRewardsAccumulated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorRewards",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "totalCreatorRewardsAccumulated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorRewards",
    data: BytesLike
  ): Result;

  events: {
    "CreatorRewardsWithdrawal(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatorRewardsWithdrawal"): EventFragment;
}

export type CreatorRewardsWithdrawalEvent = TypedEvent<
  [string, BigNumber],
  { creator: string; amount: BigNumber }
>;

export type CreatorRewardsWithdrawalEventFilter =
  TypedEventFilter<CreatorRewardsWithdrawalEvent>;

export interface ICreatorAccess extends BaseContract {
  contractName: "ICreatorAccess";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICreatorAccessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    totalCreatorRewardsAccumulated(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawCreatorRewards(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  totalCreatorRewardsAccumulated(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawCreatorRewards(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    totalCreatorRewardsAccumulated(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawCreatorRewards(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "CreatorRewardsWithdrawal(address,uint256)"(
      creator?: string | null,
      amount?: BigNumberish | null
    ): CreatorRewardsWithdrawalEventFilter;
    CreatorRewardsWithdrawal(
      creator?: string | null,
      amount?: BigNumberish | null
    ): CreatorRewardsWithdrawalEventFilter;
  };

  estimateGas: {
    totalCreatorRewardsAccumulated(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawCreatorRewards(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    totalCreatorRewardsAccumulated(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawCreatorRewards(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
