/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICommunity, ICommunityInterface } from "../ICommunity";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "commerceToken",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "membershipPrice",
        type: "uint256",
      },
    ],
    name: "ConfigurationUpdate",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_commerceToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_membershipPrice",
        type: "uint256",
      },
    ],
    name: "configure",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICommunity__factory {
  static readonly abi = _abi;
  static createInterface(): ICommunityInterface {
    return new utils.Interface(_abi) as ICommunityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICommunity {
    return new Contract(address, _abi, signerOrProvider) as ICommunity;
  }
}
