/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICreatorAccess,
  ICreatorAccessInterface,
} from "../ICreatorAccess";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "CreatorRewardsWithdrawal",
    type: "event",
  },
  {
    inputs: [],
    name: "totalCreatorRewardsAccumulated",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawCreatorRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICreatorAccess__factory {
  static readonly abi = _abi;
  static createInterface(): ICreatorAccessInterface {
    return new utils.Interface(_abi) as ICreatorAccessInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICreatorAccess {
    return new Contract(address, _abi, signerOrProvider) as ICreatorAccess;
  }
}
