/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IProtocolPolicy,
  IProtocolPolicyInterface,
} from "../IProtocolPolicy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "feeNumerator",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeDenomerator",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "setter",
        type: "address",
      },
    ],
    name: "ProtocolFeePolicyUpdate",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "feeNumerator",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeDenomerator",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "address",
        name: "setter",
        type: "address",
      },
    ],
    name: "setProtocolFeePolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IProtocolPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolPolicyInterface {
    return new utils.Interface(_abi) as IProtocolPolicyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolPolicy {
    return new Contract(address, _abi, signerOrProvider) as IProtocolPolicy;
  }
}
